### ISSUE TITLE
.NET Framework 版本过低

### ISSUE THREAD

**Issue by 28111600** [DinoChan/Kino.Toolkit.Wpf#40]
项目中用到了 `C# 7.1` 的语法糖，如:

```c#
Matrix trans = default;
```

建议修改框架为 `.NET Framework4.7` ，否则无法成功编译。

**Comment by DinoChan** [comment]
谢谢指正。

最近用了VS2019不小心把一些代码自动格式化了，导致VS2017不能编译。
