### ISSUE TITLE
有没有针对wpf嵌入web最优方式。

### ISSUE THREAD

**Issue by flash168** [DinoChan/Kino.Toolkit.Wpf#46]
内容如题，项目经常遇见嵌入地图或者其他第三方内容，嵌入方式都是web内容放在窗体内交互。有没有做过类似web嵌入项目，一起交流下。

**Comment by DinoChan** [comment]
可以加群714704041交流交流，这是HandyControl的交流群，对WPF的讨论十分活跃

**Comment by flash168** [comment]
我靠，进群还收费。收费还挺贵。



---原始邮件---
发件人: "Dino Chan"<notifications@github.com&gt;
发送时间: 2020年12月1日(周二) 上午9:41
收件人: "DinoChan/Kino.Toolkit.Wpf"<Kino.Toolkit.Wpf@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"499297357"<499297357@qq.com&gt;;
主题: Re: [DinoChan/Kino.Toolkit.Wpf] 有没有针对wpf嵌入web最优方式。 (#46)




 
可以加群714704041交流交流，这是HandyControl的交流群，对WPF的讨论十分活跃

**Comment by DinoChan** [comment]
呃，原来已经开始收费了，我都没发现……因为我不常做web交互，所以这个话题也帮不了你
